CREATE DATABASE projetofinal

USE projetofinal

CREATE TABLE funcionarios(
	cpf_funcionario CHAR(11) NOT NULL,
	nome_funcionario VARCHAR(120) NOT NULL,
	rg_funcionario VARCHAR(12) NOT NULL,
	telefone_funcionario VARCHAR(11) NOT NULL,
	email_funcionario VARCHAR(50),
	senha_funcionario VARCHAR(10) NOT NULL,
	nivel_acesso INT NOT NULL DEFAULT(1),
	PRIMARY KEY(cpf_funcionario),
	CONSTRAINT checa_acesso CHECK(nivel_acesso = 1 OR nivel_acesso = 2 OR nivel_acesso = 3)
)

INSERT INTO funcionarios VALUES('44919958617','Mateus Andrade','382560723','25616406','email@email.com','1234', '1')
INSERT INTO funcionarios VALUES('1234', 'MASTER' ,'123456789','99999999','master@master.com', '1234', '1')


CREATE TABLE materiais(
	CODIGO_MATERIAL INT NOT NULL IDENTITY(1,1),
	NOME_MATERIAL VARCHAR(120) NOT NULL,
	QTD_MATERIAL INT NOT NULL CHECK(QTD_MATERIAL>0),
	PRIMARY KEY(CODIGO_MATERIAL)
)


CREATE TABLE requisicao(
	CODIGO_REQUISICAO INT NOT NULL,
	CPF_FUNCIONARIO CHAR(11) NOT NULL,
	DATA_REQUISICAO DATE NOT NULL,
	DATA_DEVOLUCAO DATE,
	PRIMARY KEY(CODIGO_REQUISICAO),
	FOREIGN KEY(CPF_FUNCIONARIO) REFERENCES funcionarios(CPF_FUNCIONARIO)
)

INSERT INTO requisicao VALUES ('1','44919958617', '18-06-2016', NULL)
INSERT INTO requisicao VALUES ('2','42666396860', '18-06-2016', NULL)


CREATE TABLE ItensRequisicao(
	CODIGO_MATERIAL INT NOT NULL,
	CODIGO_REQUISICAO INT NOT NULL,
	CODIGO_ItensRequisicao INT NOT NULL IDENTITY,
	QTD_MATERIAL_SOLICITADO INT NOT NULL CHECK(QTD_MATERIAL_SOLICITADO>0),

	FOREIGN KEY(CODIGO_MATERIAL) REFERENCES materiais(CODIGO_MATERIAL),
	FOREIGN KEY(CODIGO_REQUISICAO) REFERENCES requisicao(CODIGO_REQUISICAO),
)


SELECT * FROM ItensRequisicao
SELECT * FROM requisicao
SELECT * FROM materiais
SELECT * FROM funcionarios

SELECT * FROM funcionarios WHERE cpf_funcionario = ?